### Opprett bruker
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "Ola Nordman",
  "email": "ola@gmail.com"
}


### Hent bruker 0
GET http://localhost:8080/users/0
Accept: application/json