spring:
  data:
    redis:
      host: localhost
      port: 6379

  docker:
    compose:
      enabled: true
      file: C:/Dev/DAT250/backend/docker-compose.yml
      lifecycle-management: start_and_stop

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest




